version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1

  pre_build:
    commands:
      - echo Restore started on `date`
      - cd AWSPriceListReservedInstanceHelper
      - dotnet clean
      - dotnet restore
      - mkdir -p .aws-sam
      - mkdir -p .aws-sam/output
      
  build:
    commands:
      - echo Build started on `date`
      - sam build --template-file AWSPriceListReservedInstanceHelper.template --region $AWS_REGION
      - sam package --kms-key-id $CODEBUILD_KMS_KEY_ID --s3-bucket $BUCKET --s3-prefix "${PROJECT_NAME}/" --use-json --region $AWS_REGION --output-template-file .aws-sam/output/$PROJECT_NAME.template 

artifacts:
  name: BuildOutput
  files:
    - AWSPriceListReservedInstanceHelper/.aws-sam/output/$PROJECT_NAME.template
  discard-paths: yes  