version: 0.2

env:
  exported-variables:
    - S3_URLS

phases:
  install:
    runtime-versions:
      dotnet: 3.1

  pre_build:
    commands:
      - echo Restore started on `date`
      - cd AWSPriceListReservedInstanceHelper
      - dotnet clean
      - dotnet restore
      - mkdir -p .aws-sam
      - mkdir -p .aws-sam/output
      
  build:
    commands:
      - echo Build started on `date`
      - sam build --template-file AWSPriceListReservedInstanceHelper.template --region $AWS_REGION
      - sam package --kms-key-id $CODEBUILD_KMS_KEY_ID --s3-bucket $BUCKET --s3-prefix "${PROJECT_NAME}/" --use-json --region $AWS_REGION --output-template-file .aws-sam/output/$PROJECT_NAME.template 

  post_build:
    commands:
      - uris=$(cat AWSPriceListReservedInstanceHelper/.aws-sam/output/$PROJECT_NAME.template | jq -r '.Resources[] | select(.Type=="AWS::Serverless::Function") | .Properties.CodeUri')
      - for i in $uris; do S3_URLS="$i,$S3_URLS; bucket=$(echo $i | awk -F/ '{print $3}'); key=$(echo $i | cut -d / -f 4-); aws s3api put-object-acl --acl bucket-owner-full-control --bucket $bucket --key $key; done
      - S3_URLS=${S3_URLS%,}

artifacts:
  name: BuildOutput
  files:
    - AWSPriceListReservedInstanceHelper/.aws-sam/output/$PROJECT_NAME.template
  discard-paths: yes  