version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
      - export PATH="$PATH:/root/.dotnet/tools"

  pre_build:
    commands:
      - echo Restore started on `date`
      - cd AWSPriceListReservedInstanceHelper
      - dotnet clean
      - dotnet restore
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet lambda package-ci --configuration Release --framework netcoreapp3.1 --s3-bucket $BUCKET --s3-prefix "${PROJECT_NAME}/" --template AWSPriceListReservedInstanceHelper.template --output-template bin/Release/netcoreapp3.1/$PROJECT_NAME.template

artifacts:
  name: BuildOutput
  files:
    - AWSPriceListReservedInstanceHelper/bin/Release/netcoreapp3.1/$PROJECT_NAME.template
  discard-paths: yes  